version: '3.8'

services:
  db:
    image: postgres:15
    container_name: aak-fullstack-db
    environment:
      POSTGRES_DB: aak_fullstack
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: aak-fullstack-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=1
      - DB_NAME=aak_fullstack
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
  
  frontend:
    build: ./frontend
    container_name: aak-fullstack-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=true
      - WDS_SOCKER_HOST=localhost
      - WDS_SOCKER_HOST=3000
    depends_on:
      - backend
    stdin_open: true
    tty: true

volumes:
  postgres_data:
  frontend_node_modules:
